#
# Standard Makefile for a hymn
#

#
# The following variables are probably all that needs to be customized for any season
#

ROOT_DIR = ..

#
# The following are the products for each piece
#

VESPERS_LILYPOND_PRODUCTS := \
  vespers_number_2.pdf \
  vespers_number_2_all.mid \
  vespers_number_2_solo.mid \
  vespers_number_2_soprano_1.mid \
  vespers_number_2_soprano_2.mid \
  vespers_number_2_alto_1.mid \
  vespers_number_2_alto_2.mid \
  vespers_number_2_tenor_1.mid \
  vespers_number_2_tenor_2.mid \
  vespers_number_2_bass_1.mid \
  vespers_number_2_bass_2.mid

VESPERS_TRACKS := \
  vespers_number_2_all.mp3 \
  vespers_number_2_solo.mp3 \
  vespers_number_2_soprano_1.mp3 \
  vespers_number_2_soprano_2.mp3 \
  vespers_number_2_alto_1.mp3 \
  vespers_number_2_alto_2.mp3 \
  vespers_number_2_tenor_1.mp3 \
  vespers_number_2_tenor_2.mp3 \
  vespers_number_2_bass_1.mp3 \
  vespers_number_2_bass_2.mp3

O_NATA_LUX_LILYPOND_PRODUCTS := \
  o_nata_lux.pdf \
  o_nata_lux_all.mid \
  o_nata_lux_soprano_1.mid \
  o_nata_lux_soprano_2.mid \
  o_nata_lux_alto_1.mid \
  o_nata_lux_alto_2.mid \
  o_nata_lux_tenor_1.mid \
  o_nata_lux_tenor_2.mid \
  o_nata_lux_bass_1.mid \
  o_nata_lux_bass_2.mid

O_NATA_LUX_TRACKS := \
  o_nata_lux_all.mp3 \
  o_nata_lux_soprano_1.mp3 \
  o_nata_lux_soprano_2.mp3 \
  o_nata_lux_alto_1.mp3 \
  o_nata_lux_alto_2.mp3 \
  o_nata_lux_tenor_1.mp3 \
  o_nata_lux_tenor_2.mp3 \
  o_nata_lux_bass_1.mp3 \
  o_nata_lux_bass_2.mp3

MY_GOD_IS_A_ROCK_LILYPOND_PRODUCTS := \
  my_god_is_a_rock.pdf \
  my_god_is_a_rock_all.mid \
  my_god_is_a_rock_solo_one.mid \
  my_god_is_a_rock_solo_two.mid \
  my_god_is_a_rock_soprano_1.mid \
  my_god_is_a_rock_soprano_2.mid \
  my_god_is_a_rock_alto_1.mid \
  my_god_is_a_rock_alto_2.mid \
  my_god_is_a_rock_tenor_1.mid \
  my_god_is_a_rock_tenor_2.mid \
  my_god_is_a_rock_bass_1.mid \
  my_god_is_a_rock_bass_2.mid

MY_GOD_IS_A_ROCK_TRACKS := \
  my_god_is_a_rock_all.mp3 \
  my_god_is_a_rock_baritone_solo.mp3 \
  my_god_is_a_rock_soprano_solo.mp3 \
  my_god_is_a_rock_soprano_1.mp3 \
  my_god_is_a_rock_soprano_2.mp3 \
  my_god_is_a_rock_alto_1.mp3 \
  my_god_is_a_rock_alto_2.mp3 \
  my_god_is_a_rock_tenor_1.mp3 \
  my_god_is_a_rock_tenor_2.mp3 \
  my_god_is_a_rock_bass_1.mp3 \
  my_god_is_a_rock_bass_2.mp3

IN_CHRIST_ALONE_LILYPOND_PRODUCTS := \
  in_christ_alone.pdf \
  in_christ_alone_all.mid \
  in_christ_alone_solo.mid \
  in_christ_alone_tenor_1.mid \
  in_christ_alone_tenor_2.mid \
  in_christ_alone_tenor_3.mid \
  in_christ_alone_tenor_4.mid \
  in_christ_alone_bass_1.mid \
  in_christ_alone_bass_2.mid \
  in_christ_alone_bass_3.mid \
  in_christ_alone_bass_4.mid

IN_CHRIST_ALONE_TRACKS := \
  in_christ_alone_all.mp3 \
  in_christ_alone_solo.mp3 \
  in_christ_alone_tenor_1.mp3 \
  in_christ_alone_tenor_2.mp3 \
  in_christ_alone_tenor_3.mp3 \
  in_christ_alone_tenor_4.mp3 \
  in_christ_alone_bass_1.mp3 \
  in_christ_alone_bass_2.mp3 \
  in_christ_alone_bass_3.mp3 \
  in_christ_alone_bass_4.mp3

GLOW_LILYPOND_PRODUCTS := \
  glow.pdf \
  glow_all.mid \
  glow_soprano.mid \
  glow_alto.mid \
  glow_tenor.mid \
  glow_bass.mid \

GLOW_TRACKS := \
  glow_all.mp3 \
  glow_soprano.mp3 \
  glow_alto.mp3 \
  glow_tenor.mp3 \
  glow_bass.mp3 \

LULLABY_LILYPOND_PRODUCTS := \
  lullaby.pdf \
  lullaby_all.mid \
  lullaby_soprano_1.mid \
  lullaby_soprano_2.mid \
  lullaby_alto_1.mid \
  lullaby_alto_2.mid \
  lullaby_tenor_1.mid \
  lullaby_tenor_2.mid \
  lullaby_bass_1.mid \
  lullaby_bass_2.mid \
  lullaby_piano.mid

LULLABY_TRACKS := \
  lullaby_all.mp3 \
  lullaby_soprano_1.mp3 \
  lullaby_soprano_2.mp3 \
  lullaby_alto_1.mp3 \
  lullaby_alto_2.mp3 \
  lullaby_tenor_1.mp3 \
  lullaby_tenor_2.mp3 \
  lullaby_bass_1.mp3 \
  lullaby_bass_2.mp3 \
  lullaby_piano.mp3

DAYS_OF_BEAUTY_LILYPOND_PRODUCTS := \
  days_of_beauty.pdf \
  days_of_beauty_all.mid \
  days_of_beauty_soprano_1.mid \
  days_of_beauty_soprano_2.mid \
  days_of_beauty_alto_1.mid \
  days_of_beauty_alto_2.mid

DAYS_OF_BEAUTY_TRACKS := \
  days_of_beauty_all.mp3 \
  days_of_beauty_soprano_1.mp3 \
  days_of_beauty_soprano_2.mp3 \
  days_of_beauty_alto_1.mp3 \
  days_of_beauty_alto_2.mp3

THE_ROSE_LILYPOND_PRODUCTS := \
  the_rose.pdf \
  the_rose_all.mid \
  the_rose_soprano_1.mid \
  the_rose_soprano_2.mid \
  the_rose_alto_1.mid \
  the_rose_alto_2.mid \
  the_rose_tenor_1.mid \
  the_rose_tenor_2.mid \
  the_rose_bass_1.mid \
  the_rose_bass_2.mid

THE_ROSE_TRACKS := \
  the_rose_all.mp3 \
  the_rose_soprano_1.mp3 \
  the_rose_soprano_2.mp3 \
  the_rose_alto_1.mp3 \
  the_rose_alto_2.mp3 \
  the_rose_tenor_1.mp3 \
  the_rose_tenor_2.mp3 \
  the_rose_bass_1.mp3 \
  the_rose_bass_2.mp3

ONLY_IN_SLEEP_LILYPOND_PRODUCTS := \
  only_in_sleep.pdf \
  only_in_sleep_all.mid \
  only_in_sleep_solo.mid \
  only_in_sleep_soprano_1.mid \
  only_in_sleep_soprano_2.mid \
  only_in_sleep_alto_1.mid \
  only_in_sleep_alto_2.mid \
  only_in_sleep_tenor_1.mid \
  only_in_sleep_tenor_2.mid \
  only_in_sleep_bass_1.mid \
  only_in_sleep_bass_2.mid

ONLY_IN_SLEEP_TRACKS := \
  only_in_sleep_all.mp3 \
  only_in_sleep_solo.mp3 \
  only_in_sleep_soprano_1.mp3 \
  only_in_sleep_soprano_2.mp3 \
  only_in_sleep_alto_1.mp3 \
  only_in_sleep_alto_2.mp3 \
  only_in_sleep_tenor_1.mp3 \
  only_in_sleep_tenor_2.mp3 \
  only_in_sleep_bass_1.mp3 \
  only_in_sleep_bass_2.mp3

TSHOTSHOLOZA_LILYPOND_PRODUCTS := \
  tshotsholoza.pdf \
  tshotsholoza_all.mid \
  tshotsholoza_solo.mid \
  tshotsholoza_soprano_1.mid \
  tshotsholoza_soprano_2.mid \
  tshotsholoza_alto_1.mid \
  tshotsholoza_alto_2.mid \
  tshotsholoza_tenor_1.mid \
  tshotsholoza_tenor_2.mid \
  tshotsholoza_bass_1.mid \
  tshotsholoza_bass_2.mid

TSHOTSHOLOZA_TRACKS := \
  tshotsholoza_all.mp3 \
  tshotsholoza_solo.mp3 \
  tshotsholoza_soprano_1.mp3 \
  tshotsholoza_soprano_2.mp3 \
  tshotsholoza_alto_1.mp3 \
  tshotsholoza_alto_2.mp3 \
  tshotsholoza_tenor_1.mp3 \
  tshotsholoza_tenor_2.mp3 \
  tshotsholoza_bass_1.mp3 \
  tshotsholoza_bass_2.mp3

THE_AWAKENING_LILYPOND_PRODUCTS := \
  the_awakening.pdf \
  the_awakening_all.mid \
  the_awakening_soprano_1.mid \
  the_awakening_soprano_2.mid \
  the_awakening_alto_1.mid \
  the_awakening_alto_2.mid \
  the_awakening_tenor_1.mid \
  the_awakening_tenor_2.mid \
  the_awakening_bass_1.mid \
  the_awakening_bass_2.mid \
  the_awakening_piano.mid

THE_AWAKENING_TRACKS := \
  the_awakening_all.mp3 \
  the_awakening_soprano_1.mp3 \
  the_awakening_soprano_2.mp3 \
  the_awakening_alto_1.mp3 \
  the_awakening_alto_2.mp3 \
  the_awakening_tenor_1.mp3 \
  the_awakening_tenor_2.mp3 \
  the_awakening_bass_1.mp3 \
  the_awakening_bass_2.mp3 \
  the_awakening_piano.mp3

# Shouldn't need to edit the following macros

LIBRARY_DIR = $(ROOT_DIR)/../LilypondTemplates
LIBRARY_FILES = $(LIBRARY_DIR)/functions.ly $(LIBRARY_DIR)/hymns.ly $(LIBRARY_DIR)/standard-elements.ly
LILYPOND = lilypond.exe
LILYPOND_PROD_OPTIONS = -dno-point-and-click -ddelete-intermediate-files
SOUNDFONT = /usr/share/sounds/sf2/FluidR3_GM.sf2

include common.mk

.PHONY: local prod clean prodclean

local: \
 $(VESPERS_TRACKS) \
 $(O_NATA_LUX_TRACKS) \
 $(MY_GOD_IS_A_ROCK_TRACKS) \
 $(IN_CHRIST_ALONE_TRACKS) \
 $(GLOW_TRACKS) \
 $(LULLABY_TRACKS) \
 $(DAYS_OF_BEAUTY_TRACKS) \
 $(THE_ROSE_TRACKS) \
 $(ONLY_IN_SLEEP_TRACKS) \
 $(TSHOTSHOLOZA_TRACKS) \
 $(THE_AWAKENING_TRACKS)

%.wav: %.mid
	fluidsynth -F $@ $(SOUNDFONT) $<

%.mp3: %.wav
	lame -V2 $< $@

clean:
	-rm *.pdf
	-rm *.mid
	-rm *.mp3
	-rm *.wav

#
# Vespers 2 rules
#

$(VESPERS_LILYPOND_PRODUCTS): vespers_number_2.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

vespers_number_2_all.mp3: vespers_number_2_all.wav

vespers_number_2_all.wav: vespers_number_2_all.mid

vespers_number_2_solo.mp3: vespers_number_2_solo.wav

vespers_number_2_solo.wav: vespers_number_2_solo.mid

vespers_number_2_soprano_1.mp3: vespers_number_2_soprano_1.wav

vespers_number_2_soprano_1.wav: vespers_number_2_soprano_1.mid

vespers_number_2_soprano_2.mp3: vespers_number_2_soprano_2.wav

vespers_number_2_soprano_2.wav: vespers_number_2_soprano_2.mid

vespers_number_2_alto_1.mp3: vespers_number_2_alto_1.wav

vespers_number_2_alto_1.wav: vespers_number_2_alto_1.mid

vespers_number_2_alto_2.mp3: vespers_number_2_alto_2.wav

vespers_number_2_alto_2.wav: vespers_number_2_alto_2.mid

vespers_number_2_tenor_1.mp3: vespers_number_2_tenor_1.wav

vespers_number_2_tenor_1.wav: vespers_number_2_tenor_1.mid

vespers_number_2_tenor_2.mp3: vespers_number_2_tenor_2.wav

vespers_number_2_tenor_2.wav: vespers_number_2_tenor_2.mid

vespers_number_2_bass_1.mp3: vespers_number_2_bass_1.wav

vespers_number_2_bass_1.wav: vespers_number_2_bass_1.mid

vespers_number_2_bass_2.mp3: vespers_number_2_bass_2.wav

vespers_number_2_bass_2.wav: vespers_number_2_bass_2.mid

#
# O Nata Lux rules
#

$(O_NATA_LUX_LILYPOND_PRODUCTS): o_nata_lux.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

o_nata_lux_all.mp3: o_nata_lux_all.wav

o_nata_lux_all.wav: o_nata_lux_all.mid

o_nata_lux_soprano_1.mp3: o_nata_lux_soprano_1.wav

o_nata_lux_soprano_1.wav: o_nata_lux_soprano_1.mid

o_nata_lux_soprano_2.mp3: o_nata_lux_soprano_2.wav

o_nata_lux_soprano_2.wav: o_nata_lux_soprano_2.mid

o_nata_lux_alto_1.mp3: o_nata_lux_alto_1.wav

o_nata_lux_alto_1.wav: o_nata_lux_alto_1.mid

o_nata_lux_alto_2.mp3: o_nata_lux_alto_2.wav

o_nata_lux_alto_2.wav: o_nata_lux_alto_2.mid

o_nata_lux_tenor_1.mp3: o_nata_lux_tenor_1.wav

o_nata_lux_tenor_1.wav: o_nata_lux_tenor_1.mid

o_nata_lux_tenor_2.mp3: o_nata_lux_tenor_2.wav

o_nata_lux_tenor_2.wav: o_nata_lux_tenor_2.mid

o_nata_lux_bass_1.mp3: o_nata_lux_bass_1.wav

o_nata_lux_bass_1.wav: o_nata_lux_bass_1.mid

o_nata_lux_bass_2.mp3: o_nata_lux_bass_2.wav

o_nata_lux_bass_2.wav: o_nata_lux_bass_2.mid

#
# My God is a Rock rules
#

$(MY_GOD_IS_A_ROCK_LILYPOND_PRODUCTS): my_god_is_a_rock.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

my_god_is_a_rock_all.mp3: my_god_is_a_rock_all.wav

my_god_is_a_rock_all.wav: my_god_is_a_rock_all.mid

my_god_is_a_rock_baritone_solo.mp3: my_god_is_a_rock_baritone_solo.wav
	lame -V2 $< $@

my_god_is_a_rock_baritone_solo.wav: my_god_is_a_rock_solo_one.mid
	fluidsynth -F $@ $(SOUNDFONT) $<

my_god_is_a_rock_soprano_solo.mp3: my_god_is_a_rock_solo_two.wav
	lame -V2 $< $@

my_god_is_a_rock_soprano_solo.wav: my_god_is_a_rock_solo_two.mid
	fluidsynth -F $@ $(SOUNDFONT) $<

my_god_is_a_rock_soprano_1.mp3: my_god_is_a_rock_soprano_1.wav

my_god_is_a_rock_soprano_1.wav: my_god_is_a_rock_soprano_1.mid

my_god_is_a_rock_soprano_2.mp3: my_god_is_a_rock_soprano_2.wav

my_god_is_a_rock_soprano_2.wav: my_god_is_a_rock_soprano_2.mid

my_god_is_a_rock_alto_1.mp3: my_god_is_a_rock_alto_1.wav

my_god_is_a_rock_alto_1.wav: my_god_is_a_rock_alto_1.mid

my_god_is_a_rock_alto_2.mp3: my_god_is_a_rock_alto_2.wav

my_god_is_a_rock_alto_2.wav: my_god_is_a_rock_alto_2.mid

my_god_is_a_rock_tenor_1.mp3: my_god_is_a_rock_tenor_1.wav

my_god_is_a_rock_tenor_1.wav: my_god_is_a_rock_tenor_1.mid

my_god_is_a_rock_tenor_2.mp3: my_god_is_a_rock_tenor_2.wav

my_god_is_a_rock_tenor_2.wav: my_god_is_a_rock_tenor_2.mid

my_god_is_a_rock_bass_1.mp3: my_god_is_a_rock_bass_1.wav

my_god_is_a_rock_bass_1.wav: my_god_is_a_rock_bass_1.mid

my_god_is_a_rock_bass_2.mp3: my_god_is_a_rock_bass_2.wav

my_god_is_a_rock_bass_2.wav: my_god_is_a_rock_bass_2.mid

#
# In Christ Alone Rules
#

$(IN_CHRIST_ALONE_LILYPOND_PRODUCTS): in_christ_alone.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

in_christ_alone_all.mp3: in_christ_alone_all.wav

in_christ_alone_all.wav: in_christ_alone_all.mid

in_christ_alone_solo.mp3: in_christ_alone_solo.wav

in_christ_alone_solo.wav: in_christ_alone_solo.mid

in_christ_alone_tenor_1.mp3: in_christ_alone_tenor_1.wav

in_christ_alone_tenor_1.wav: in_christ_alone_tenor_1.mid

in_christ_alone_tenor_2.mp3: in_christ_alone_tenor_2.wav

in_christ_alone_tenor_2.wav: in_christ_alone_tenor_2.mid

in_christ_alone_tenor_3.mp3: in_christ_alone_tenor_3.wav

in_christ_alone_tenor_3.wav: in_christ_alone_tenor_3.mid

in_christ_alone_tenor_4.mp3: in_christ_alone_tenor_4.wav

in_christ_alone_tenor_4.wav: in_christ_alone_tenor_4.mid

in_christ_alone_bass_1.mp3: in_christ_alone_bass_1.wav

in_christ_alone_bass_1.wav: in_christ_alone_bass_1.mid

in_christ_alone_bass_2.mp3: in_christ_alone_bass_2.wav

in_christ_alone_bass_2.wav: in_christ_alone_bass_2.mid

in_christ_alone_bass_3.mp3: in_christ_alone_bass_3.wav

in_christ_alone_bass_3.wav: in_christ_alone_bass_3.mid

in_christ_alone_bass_4.mp3: in_christ_alone_bass_4.wav

in_christ_alone_bass_4.wav: in_christ_alone_bass_4.mid

#
# Glow rules
#

$(GLOW_LILYPOND_PRODUCTS): glow.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

glow_all.mp3: glow_all.wav

glow_all.wav: glow_all.mid

glow_soprano.mp3: glow_soprano.wav

glow_soprano.wav: glow_soprano.mid

glow_alto.mp3: glow_alto.wav

glow_alto.wav: glow_alto.mid

glow_tenor.mp3: glow_tenor.wav

glow_tenor.wav: glow_tenor.mid

glow_bass.mp3: glow_bass.wav

glow_bass.wav: glow_bass.mid

#
# Lullaby rules
#

$(LULLABY_LILYPOND_PRODUCTS): lullaby.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

lullaby_all.mp3: lullaby_all.wav

lullaby_all.wav: lullaby_all.mid

lullaby_soprano_1.mp3: lullaby_soprano_1.wav

lullaby_soprano_1.wav: lullaby_soprano_1.mid

lullaby_soprano_2.mp3: lullaby_soprano_2.wav

lullaby_soprano_2.wav: lullaby_soprano_2.mid

lullaby_alto_1.mp3: lullaby_alto_1.wav

lullaby_alto_1.wav: lullaby_alto_1.mid

lullaby_alto_2.mp3: lullaby_alto_2.wav

lullaby_alto_2.wav: lullaby_alto_2.mid

lullaby_tenor_1.mp3: lullaby_tenor_1.wav

lullaby_tenor_1.wav: lullaby_tenor_1.mid

lullaby_tenor_2.mp3: lullaby_tenor_2.wav

lullaby_tenor_2.wav: lullaby_tenor_2.mid

lullaby_bass_1.mp3: lullaby_bass_1.wav

lullaby_bass_1.wav: lullaby_bass_1.mid

lullaby_bass_2.mp3: lullaby_bass_2.wav

lullaby_bass_2.wav: lullaby_bass_2.mid

lullaby_piano.mp3: lullaby_piano.wav

lullaby_piano.wav: lullaby_piano.mid

#
# Days of Beauty rules
#

$(DAYS_OF_BEAUTY_LILYPOND_PRODUCTS): days_of_beauty.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

days_of_beauty_all.mp3: days_of_beauty_all.wav

days_of_beauty_all.wav: days_of_beauty_all.mid

days_of_beauty_soprano_1.mp3: days_of_beauty_soprano_1.wav

days_of_beauty_soprano_1.wav: days_of_beauty_soprano_1.mid

days_of_beauty_soprano_2.mp3: days_of_beauty_soprano_2.wav

days_of_beauty_soprano_2.wav: days_of_beauty_soprano_2.mid

days_of_beauty_alto_1.mp3: days_of_beauty_alto_1.wav

days_of_beauty_alto_1.wav: days_of_beauty_alto_1.mid

days_of_beauty_alto_2.mp3: days_of_beauty_alto_2.wav

days_of_beauty_alto_2.wav: days_of_beauty_alto_2.mid

#
# The Rose rules
#

$(THE_ROSE_LILYPOND_PRODUCTS): the_rose.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

the_rose_all.mp3: the_rose_all.wav

the_rose_all.wav: the_rose_all.mid

the_rose_soprano_1.mp3: the_rose_soprano_1.wav

the_rose_soprano_1.wav: the_rose_soprano_1.mid

the_rose_soprano_2.mp3: the_rose_soprano_2.wav

the_rose_soprano_2.wav: the_rose_soprano_2.mid

the_rose_alto_1.mp3: the_rose_alto_1.wav

the_rose_alto_1.wav: the_rose_alto_1.mid

the_rose_alto_2.mp3: the_rose_alto_2.wav

the_rose_alto_2.wav: the_rose_alto_2.mid

the_rose_tenor_1.mp3: the_rose_tenor_1.wav

the_rose_tenor_1.wav: the_rose_tenor_1.mid

the_rose_tenor_2.mp3: the_rose_tenor_2.wav

the_rose_tenor_2.wav: the_rose_tenor_2.mid

the_rose_bass_1.mp3: the_rose_bass_1.wav

the_rose_bass_1.wav: the_rose_bass_1.mid

the_rose_bass_2.mp3: the_rose_bass_2.wav

the_rose_bass_2.wav: the_rose_bass_2.mid

#
# Only in sleep rules
#

$(ONLY_IN_SLEEP_LILYPOND_PRODUCTS): only_in_sleep.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

only_in_sleep_all.mp3: only_in_sleep_all.wav

only_in_sleep_all.wav: only_in_sleep_all.mid

only_in_sleep_solo.mp3: only_in_sleep_solo.wav

only_in_sleep_solo.wav: only_in_sleep_solo.mid

only_in_sleep_soprano_1.mp3: only_in_sleep_soprano_1.wav

only_in_sleep_soprano_1.wav: only_in_sleep_soprano_1.mid

only_in_sleep_soprano_2.mp3: only_in_sleep_soprano_2.wav

only_in_sleep_soprano_2.wav: only_in_sleep_soprano_2.mid

only_in_sleep_alto_1.mp3: only_in_sleep_alto_1.wav

only_in_sleep_alto_1.wav: only_in_sleep_alto_1.mid

only_in_sleep_alto_2.mp3: only_in_sleep_alto_2.wav

only_in_sleep_alto_2.wav: only_in_sleep_alto_2.mid

only_in_sleep_tenor_1.mp3: only_in_sleep_tenor_1.wav

only_in_sleep_tenor_1.wav: only_in_sleep_tenor_1.mid

only_in_sleep_tenor_2.mp3: only_in_sleep_tenor_2.wav

only_in_sleep_tenor_2.wav: only_in_sleep_tenor_2.mid

only_in_sleep_bass_1.mp3: only_in_sleep_bass_1.wav

only_in_sleep_bass_1.wav: only_in_sleep_bass_1.mid

only_in_sleep_bass_2.mp3: only_in_sleep_bass_2.wav

only_in_sleep_bass_2.wav: only_in_sleep_bass_2.mid

#
# Tshotsholoza rules
#

$(TSHOTSHOLOZA_LILYPOND_PRODUCTS): tshotsholoza.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

tshotsholoza_all.mp3: tshotsholoza_all.wav

tshotsholoza_all.wav: tshotsholoza_all.mid

tshotsholoza_solo.mp3: tshotsholoza_solo.wav

tshotsholoza_solo.wav: tshotsholoza_solo.mid

tshotsholoza_soprano_1.mp3: tshotsholoza_soprano_1.wav

tshotsholoza_soprano_1.wav: tshotsholoza_soprano_1.mid

tshotsholoza_soprano_2.mp3: tshotsholoza_soprano_2.wav

tshotsholoza_soprano_2.wav: tshotsholoza_soprano_2.mid

tshotsholoza_alto_1.mp3: tshotsholoza_alto_1.wav

tshotsholoza_alto_1.wav: tshotsholoza_alto_1.mid

tshotsholoza_alto_2.mp3: tshotsholoza_alto_2.wav

tshotsholoza_alto_2.wav: tshotsholoza_alto_2.mid

tshotsholoza_tenor_1.mp3: tshotsholoza_tenor_1.wav

tshotsholoza_tenor_1.wav: tshotsholoza_tenor_1.mid

tshotsholoza_tenor_2.mp3: tshotsholoza_tenor_2.wav

tshotsholoza_tenor_2.wav: tshotsholoza_tenor_2.mid

tshotsholoza_bass_1.mp3: tshotsholoza_bass_1.wav

tshotsholoza_bass_1.wav: tshotsholoza_bass_1.mid

tshotsholoza_bass_2.mp3: tshotsholoza_bass_2.wav

tshotsholoza_bass_2.wav: tshotsholoza_bass_2.mid

#
# The Awakening rules
#

$(THE_AWAKENING_LILYPOND_PRODUCTS): the_awakening.ly
	$(LILYPOND) $(LILYPOND_PROD_OPTIONS) $<

the_awakening_all.mp3: the_awakening_all.wav

the_awakening_all.wav: the_awakening_all.mid

the_awakening_soprano_1.mp3: the_awakening_soprano_1.wav

the_awakening_soprano_1.wav: the_awakening_soprano_1.mid

the_awakening_soprano_2.mp3: the_awakening_soprano_2.wav

the_awakening_soprano_2.wav: the_awakening_soprano_2.mid

the_awakening_alto_1.mp3: the_awakening_alto_1.wav

the_awakening_alto_1.wav: the_awakening_alto_1.mid

the_awakening_alto_2.mp3: the_awakening_alto_2.wav

the_awakening_alto_2.wav: the_awakening_alto_2.mid

the_awakening_tenor_1.mp3: the_awakening_tenor_1.wav

the_awakening_tenor_1.wav: the_awakening_tenor_1.mid

the_awakening_tenor_2.mp3: the_awakening_tenor_2.wav

the_awakening_tenor_2.wav: the_awakening_tenor_2.mid

the_awakening_bass_1.mp3: the_awakening_bass_1.wav

the_awakening_bass_1.wav: the_awakening_bass_1.mid

the_awakening_bass_2.mp3: the_awakening_bass_2.wav

the_awakening_bass_2.wav: the_awakening_bass_2.mid

the_awakening_piano.mp3: the_awakening_piano.wav

the_awakening_piano.wav: the_awakening_piano.mid
